### ISSUE TITLE
lib-tflite does not compile,  fatal error: tensorflow/lite/allocation.h: No such file or directory

### ISSUE THREAD

**Issue by arush15june** [unikraft/lib-tflite#2]
I've been trying to build tflite in a newly init-ed app, however, it fails with the following error.

```
[DEBUG   ] make -C /home/ubuntu/.unikraft/unikraft A=/home/ubuntu/tflite L=/home/ubuntu/.unikraft/libs/tflite:/home/ubuntu/.unikraft/libs/pthread-embedded:/home/ubuntu/.unikraft/libs/libcxx:/home/ubuntu/.unikraft/libs/newlib:/home/ubuntu/.unikraft/libs/libcxxabi:/home/ubuntu/.unikraft/libs/libunwind:/home/ubuntu/.unikraft/libs/compiler-rt
CXX     libtflite: allocation.o
     1% █▋                                                                                                                                                               2/194 [ 4.55file/s
/home/ubuntu/tflite/build/libtflite/origin/tensorflow-2.0.1/tensorflow/lite/allocation.cc:16:10: fatal error: tensorflow/lite/allocation.h: No such file or directory
   16 | #include "tensorflow/lite/allocation.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [/home/ubuntu/.unikraft/unikraft/support/build/Makefile.build:27: /home/ubuntu/tflite/build/libtflite/allocation.o] Error 1
make[1]: *** [Makefile:984: sub-make] Error 2
make: *** [Makefile:32: _all] Error 2
```

Any pointers on how to fix this? `allocation.h` does exist in the extracted tensorflow/lite sources.

kraft.yml
```
---
specification: '0.5'
name: tflite
unikraft:
  version: '0.5'
targets:
  - architecture: x86_64
    platform: linuxu
libraries:
  tflite:
    version: '0.5'
    kconfig:
      - CONFIG_LIBTFLITE_MAIN_FUNCTION=y
  pthread-embedded:
    version: '0.5'
  libcxx:
    version: '0.5'
  newlib:
    version: '0.5'
  libcxxabi:
    version: '0.5'
  libunwind:
    version: '0.5'
  compiler-rt:
    version: '0.5'
volumes: {}
networks: {}
```
