### ISSUE TITLE
error: compilation fails at linking due to farmash: undefined reference to __assert_fail

### ISSUE THREAD

**Issue by arush15june** [unikraft/lib-tflite#3]
I've been trying to compile lib-tflite. I have been able to get it to compile everything, however, it fails to link the image at the end due to the following error.

```
GEN     libsyscall_shim: provided_syscalls.h.in.new
LD      tflite_xen-x86_64.ld.o
OBJCOPY tflite_xen-x86_64.o
LD      tflite_xen-x86_64.dbg
    25% ████████████████████████████████████████▎                                                                                                                         9/36 [ 2.39file/s]/usr/bin/ld: /home/charge/tflite/build/tflite_xen-x86_64.o: in function `farmhashna::Hash64(char const*, unsigned long)':
/home/charge/tflite/build/libfarmhash/origin/farmhash-816a4ae622e964763ca0862d9dbd19324a1eaf45/src/farmhash.cc:537: undefined reference to `__assert_fail'
/usr/bin/ld: /home/charge/tflite/build/tflite_xen-x86_64.o: in function `farmhashuo::Hash64WithSeeds(char const*, unsigned long, unsigned long, unsigned long)':
/home/charge/tflite/build/libfarmhash/origin/farmhash-816a4ae622e964763ca0862d9dbd19324a1eaf45/src/farmhash.cc:612: undefined reference to `__assert_fail'
collect2: error: ld returned 1 exit status
make[1]: *** [/home/charge/.unikraft/unikraft/plat/xen/Linker.uk:25: /home/charge/tflite/build/tflite_xen-x86_64.dbg] Error 1
make: *** [Makefile:919: sub-make] Error 2
```

kraft.yml
```yaml
---
specification: '0.5'
name: tflite
unikraft:
  version: '0.4'
  kconfig:
    - CONFIG_LIBPOSIX_SYSINFO=y
targets:
  - architecture: x86_64
    platform: xen
libraries:
  pthread-embedded:
    version: '0.4'
  libunwind:
    version: '0.5'
  compiler-rt:
    version: '0.5'
  libcxx:
    version: '0.5'
  newlib:
    version: '0.5'
  libcxxabi:
    version: '0.5'
  gemmlowp:
    version: '0.5'
  flatbuffers:
    version: '0.5'
  farmhash:
    version: '0.5'
  eigen:
    version: '0.5'
  fft2d:
    version: '0.5'
  tflite:
    version: '0.5'
    kconfig:
      - CONFIG_LIBTFLITE_MAIN_FUNCTION=y
volumes: {}
networks: {}
```

Not sure how to proceed further with the farmhash undefined reference. I believe newlib should be providing __assert_fail?
